# Github Action for generating a contribution graph getting eaten by a snake

name: Generate snake

# Controls when the workflow will run
on:
  schedule:
    # Make action run every 6 hours
    - cron: "0 */6 * * *"

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sequence of runs in this workflow
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Generate the snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: wolf-361
          # Generate the files on a branch called Output To keep the maine branch from cluttering up
          gif_out_path: dist/github-contribtion-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
      
      # show the status of the build to make it easier for debugging (if ther's any issues)
      - run: git status
      
      # Push the change
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          # output branch mentionned before
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
