# GitHub action for generating Wakatime Stats for my profile readme
name: Waka Readme

# Controls when the workflow will run
on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
    
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

   # run on every push on the master branch
  push:
    branches:
    - main
  
# Sequence of runs in this workflow
jobs:
  # This workflow contains a single job called "update-readme"
  update-readme:
    # Job Name
    name: Update Readme with Metrics
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # https://github.com/anmol098/waka-readme-stats
      - uses: anmol098/waka-readme-stats@master
        with:
          # https://github.com/anmol098/waka-readme-stats
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: True
          SHOW_PROFILE_VIEWS: False
          SHOW_OS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_PROJECTS: False
          SHOW_LOC_CHART: False
          SHOW_SHORT_INFO: False
          SYMBOL_VERSION: 2
          
          
